export const ADD_ARTICLE = "ADD_ARTICLE"
export const REMOVE_ARTICLE = "REMOVE_ARTICLE"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const ON_MARK_TODO = 'ON_MARK_TODO'

export const LOAD_CARDS = 'LOAD_CARDS'
export const INCREMENT_BASKET_AMOUNTH = 'INCREMENT_BASKET_AMOUNTH'
export const DECREMENT_BASKET_AMOUNTH = 'DECREMENT_BASKET_AMOUNTH'
export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
